name: Databricks API

on:
  push:
    branches: [ main ]

jobs:
  run-databricks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Call Databricks API
        run: |
          curl -X GET https://adb-7405605185991044.4.azuredatabricks.net/api/2.0/clusters/list \
          -H "Authorization: Bearer $DATABRICKS_TOKEN"
        env:
          DATABRICKS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          CREATOR_EMAIL: ${{ secrets.CREATOR_EMAIL}}